# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_station_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QFont
from PyQt5.QtCore import Qt
from Test_table import MyTable
from count_time import ShowTime


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 774)

        pe = QPalette()
        pe.setColor(QPalette.WindowText, Qt.blue)  # 设置字体颜色
        pe.setColor(QPalette.Window, Qt.darkGray)  # 设置背景颜色

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        # loop测试按键
        self.Loop_Test_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Loop_Test_Button.sizePolicy().hasHeightForWidth())
        self.Loop_Test_Button.setSizePolicy(sizePolicy)
        self.Loop_Test_Button.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.Loop_Test_Button, 2, 2, 1, 1)

        # Normal测试按键
        self.Normal_Test_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Normal_Test_Button.sizePolicy().hasHeightForWidth())
        self.Normal_Test_Button.setSizePolicy(sizePolicy)
        self.Normal_Test_Button.setObjectName("pushButton")
        self.gridLayout.addWidget(self.Normal_Test_Button, 0, 2, 1, 1)

        # 测试模式
        self.label_model = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_model.sizePolicy().hasHeightForWidth())
        self.label_model.setSizePolicy(sizePolicy)
        self.label_model.setObjectName("label_2")
        self.label_model.setFont(QFont("Roman times", 30, QFont.Bold))
        self.label_model.setAutoFillBackground(True)  # 设置背景充满，为设置背景颜色的必要条件
        self.label_model.setPalette(pe)
        self.gridLayout.addWidget(self.label_model, 2, 0, 1, 1)

        self.serial_number_line = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_number_line.sizePolicy().hasHeightForWidth())
        self.serial_number_line.setSizePolicy(sizePolicy)
        self.serial_number_line.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.serial_number_line, 3, 0, 1, 2)

        self.Start_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Start_Button.sizePolicy().hasHeightForWidth())
        self.Start_Button.setSizePolicy(sizePolicy)
        self.Start_Button.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.Start_Button, 3, 2, 1, 1)

        # 当前测试状态
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setObjectName("label_3")
        self.label_status.setFont(QFont("Calibri", 30, QFont.Bold))
        self.gridLayout.addWidget(self.label_status, 2, 1, 1, 1)

        self.Offline_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Offline_Button.sizePolicy().hasHeightForWidth())
        self.Offline_Button.setSizePolicy(sizePolicy)
        self.Offline_Button.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.Offline_Button, 1, 2, 1, 1)

        # 测试站名称
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setObjectName("label")
        self.label_name.setFont(QFont("Roman times", 25, QFont.Bold))
        self.gridLayout.addWidget(self.label_name, 0, 0, 2, 2)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        # 计时模块
        self.label_time = ShowTime(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time.sizePolicy().hasHeightForWidth())
        self.label_time.setSizePolicy(sizePolicy)
        self.label_time.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_time)

        # Attributes模块
        self.Attributes = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Attributes.sizePolicy().hasHeightForWidth())
        self.Attributes.setSizePolicy(sizePolicy)
        self.Attributes.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.Attributes)

        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        # 测试列表模块
        self.Test_Item = MyTable(self.centralwidget)
        self.Test_Item.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.Test_Item)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 22))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Station"))
        self.label_model.setText(_translate("MainWindow", "Normal_Test"))
        self.label_status.setText(_translate("MainWindow", "Standby"))
        self.Loop_Test_Button.setText(_translate("MainWindow", "Loop_Test"))
        self.Normal_Test_Button.setText(_translate("MainWindow", "Normal_Test"))
        self.Offline_Button.setText(_translate("MainWindow", "Offline_Test"))
        self.Start_Button.setText(_translate("MainWindow", "Start"))
